### ISSUE TITLE
Licencja

### ISSUE THREAD

**Issue by psmolenski** [toudi/ksef#14]
Na jakiej licencji udostępniany jest kod?

**Comment by toudi** [comment]
nie wydaje mi się, żeby którykolwiek z moich projektów miał licencję. nie jest moją intencją obarczać użytkowników i innych programistów jakimikolwiek restrykcjami. rób z kodem co tylko Ci się podoba :)

**Comment by psmolenski** [comment]
Znakomicie! Jeżeli udostępniasz swój kod bez żadnych ograniczeń, najlepszą opcją jest licencja [MIT](https://opensource.org/license/mit/), która jest najkrótszą i najprostszą licencją. W skrócie można ją podsumować tak: `Oto kod. Weź go, uruchom, modyfikuj, sprzedawaj i rób co chcesz na własną odpowiedzialność. Nie miej do autora pretensji jeżeli coś wybuchnie`
