### ISSUE TITLE
download pdf

### ISSUE THREAD

**Issue by kuncy7** [toudi/ksef#19]
Czy to jest problem z bramką test, czy coś "oni" znowu pozmieniali??
```
ksef download-pdf -i '*' -p /u/firmatic/firmatic/KSeF/in/registry.yaml -token 2356E5A8DF63195FE4D95AB583F8D2D95D05959D996E7BF3E67E9483D9FB294B -xml
request: &{Method:GET URL:https://ksef-test.mf.gov.pl/api/online/Invoice/Get/5342134255-20240111-4C4984495458-9C Proto:HTTP/1.1 ProtoMajor:1 ProtoMinor:1 Header:map[Sessiontoken:[099b0d6141d0e5937e0c14b913c8a280b6451838df6500c72f2ad3adb6811db6]] Body:<nil> GetBody:<nil> ContentLength:0 TransferEncoding:[] Close:false Host:ksef-test.mf.gov.pl Form:map[] PostForm:map[] MultipartForm:<nil> Trailer:map[] RemoteAddr: RequestURI: TLS:<nil> Cancel:<nil> Response:<nil> ctx:{emptyCtx:{}}}
błąd wykonania -i:
unable to download PDF: unable to perform download request: Post "/web/api/invoice/get-invoice-pdf-file?ksefReferenceNumber=5342134255-20240111-4C4984495458-9C": unsupported protocol scheme ""
```
Pobiera się jedna (pierwsza faktura?) w xml, bez klucza `-xml` pdf (nawet jeden) się nie pobiera.

Podając konkretny numer xml się pobiera, pdf nie.
```
ksef download-pdf -i 'FVs-138/1/2021' -p /u/firmatic/firmatic/KSeF/in/registry.yaml -token 2356E5A8DF63195FE4D95AB583F8D2D95D05959D996E7BF3E67E9483D9FB294B
błąd wykonania -i:
unable to download PDF: unable to perform download request: Post "/web/api/invoice/get-invoice-pdf-file?ksefReferenceNumber=5342134255-20240111-26A1A80D6818-0E": unsupported protocol scheme ""
```

**Comment by toudi** [comment]
ewidentny babol, dzięki za zwrócenie uwagi

**Comment by kuncy7** [comment]
Teraz pobiera pdfy, chyba bramkę "naprawili", ale użycie klucza `-xml` dalej pobiera pdf razem z xml.
Co ciekawe jak już są pobrane pdfy w katalogu, to użycie klucza `-xml` nic nie robi.
Znaczy pdfy są nie ruszone, a xmli brak.

**Comment by toudi** [comment]
nie, to nie był błąd po stronie KSeF, to ja miałem błąd w kodzie :) zerknę na to jeszcze raz wieczorem i zobaczę - może po prostu opis flagi jest niezgodny z oczekiwanym zachowaniem.

Tak, jeśli PDF'y są pobrane to program nie pobierze ich drugi raz, ale zerknę o co chodzi z tymi xm'ami. Potrzebuję po prostu teraz więcej czasu bo od stycznia zacząłem pracę i znów robię program w trybie "po godzinach"

**Comment by kuncy7** [comment]
Dzięki za poprawioną wersję. Teraz pobiera pdfy i xml zgodnie z dokumentacją.
Temat zamykam.
