### ISSUE TITLE
Problem z kompilacją zaraz po ściagnięciu.

### ISSUE THREAD

**Issue by mocakow** [toudi/ksef#5]
Todi pozmieniałeś katalogi wiec komenda kompilacji nieco się zmieni wydaje się że może być taka:
go build -o ksef ./cmd/ksef/main.go

Niestety po wydaniu komendy rekompilującej schematy komenda zwraca bład
System na którym kompiluję to EndeavourOS czyli Archlinux 

![Screenshot_20231210_092202](https://github.com/toudi/ksef/assets/72433169/182f7b30-44c8-4d7e-af48-6fd29091b6db)

**Comment by toudi** [comment]
tak, wydaje mi się, że już to poprawiłem ale nie w branchu master. zobacz brancha `refactor-project-layout`. porządnej dokumentacji jeszcze nie zrobiłem bo robię to wszystko po godzinach więc wygląda to jak wygląda :( oraz tak, masz rację, go build jest taki jak podałeś

**Comment by toudi** [comment]
aktualnie pracuję na pobieraniem wizualizacji faktury w PDF tylko coś muszę ewidentnie robić źle bo sesja cały czas jest na statusie 310 a żeby pobrać PDF musi przeskoczyć na 315

**Comment by mocakow** [comment]
Po ściaŋnięciu brancha który podaleś też bład

cannot open dest file for writing: open internal/sei/generators/FA_1/schema_ordering.go: no such file or directory

**Comment by toudi** [comment]
właśnie zauważyłem. źródłówkę od fa_1 i tak muszę wywalić bo ministerstwo i tak nie będzie wspierać tego formatu - dlatego w kodzie jest tylko fa_2. daj mi dosłownie 10 minut bo uporałem się z PDF'ami i zaraz robię commita.

**Comment by toudi** [comment]
ok, zrób git pull i spróbuj ponownie. obecnie program wypluwa trochę informacji diagnostycznych - skończy się to jak tylko dorobię porządne logowanie przez zerolog

**Comment by mocakow** [comment]
Nadal error

cannot open dest file for writing: open internal/sei/generators/FA_2/schema_ordering.go: no such file or directory
Już wiem. W drzewie katalkogów masz fa_2 a powinno byc FA_2
Ważne żeby było duże literą przynajmniej tak się odwolujesz do katalogu.
Duże male litery to w linuxie bardzo ważne. 
Może zmień FA_2 na FA-2.
fa_2, FA_2, Fa_2, fA_2 to dla linuxa 4 różne katalogi. Linux tego nie wybacza :)

Po zmianie nazwy katalogu skompilowało się.

**Comment by toudi** [comment]
ekstra, masz rację, nie kompilowałem na linuksie tylko chwilowo na maku. dodałem poprawkę. 

tak poza tym, może nie wynika to jednoznacznie z README ale tego pliku nie musisz wcale kompilować :) tzn jeśli chcesz przebudować ze źródeł to wystarczy samo `go build`. ten nieszczęsny mały skrypt jedyne co robi to generuje kolejność elementów do sortowania XML'a ale one i tak już są w źródle programu. aczkolwiek wiadomo - zawsze lepiej że błąd jest poprawiony :D dzięki za zgłoszenie!

**Comment by mocakow** [comment]
Dodalem insue prośbę odnośnie jednego z ez żródłowych  formatów.pliku :)

W temacie kompilacji to dodać można tam w katalogu głównym skrypt
install.sh aby był wykonywalny trzeba wykonać: "chmod +x install.sh"
i w treści:
go build -o ksef ./cmd/ksef/main.go
go run parse_schemas.go

bez chmod wykonywać: "sh install.sh"  
samo go build nie wystarczy

wykonane w głównym chce pliki ”go" w katalogu

build constraints exclude all Go files in /katalogdonowy/git/ksef :(

a bezpośrednio w katalogu w którym znajduje się main.go  jest ok

**Comment by toudi** [comment]
`go build` to był skrót myślowy - oczywiście miałem na myśli pełną komendę tj. tak jak podajesz (`go build -o ksef ./cmd/ksef/main.go`) :) Ta druga komenda czyli `go run parse_schemas.go` jeśli w ogóle to powinna być wykonana *przed* kompilacją binarek tyle tylko że jeśli popatrzysz w kod źródłowy to wynik wykonania tej komendy już i tak jest zacommitowany i tej komendy w ogóle nie trzeba uruchamiać. Idea jej powstania była taka że jeśli ministerstwo po raz kolejny użyje xsd z trybem "sequence" (co wymusza sortowanie elementów w drzewie) i kolejną wersję nazwie np. FA_3.xsd to będę mógł napisać nowy generator a jako pierwszy element tego generatora powstanie właśnie pllik z kolejnością elementów. Dodałem bardziej szczegółowe wyjaśnienie tej kwestii w README aczkolwiek pewnie i tak jest to dość tajemnicze. Pracuję nad zbudowaniem porządnej dokumentacji i czytam jak mógłbym ją hostować na github, to z pewnością powinno pomóc rozwiać wszelkie wątpliwości :)
