### ISSUE TITLE
Problem z ksef status

### ISSUE THREAD

**Issue by kuncy7** [toudi/ksef#9]
Przepraszam że tak marudzę, ale sprawdzam wszystkie potrzebne mi opcje.
O ile `ksef status -p KSeF/out/registry.yaml` działa prawidłowo,
to już komenda: `ksef status -p KSeF/out/registry.yaml -o KSeF/UPO`
kończy się tak:
```
ksef status -p KSeF/out/registry.yaml -o KSeF/UPO
request URL: https://ksef-test.mf.gov.pl/api/common/Status/20231219-SE-E554A4EEA0-84C548A5FE-F4
error running status:
unable to download UPO: unable to create UPO PDF file: open KSeF/UPO: is a directory
```
Jak podam w opcji -o nazwę pliku to upo zapisuje się tam jako ten plik.
Myślałem że po "-o" powinien być katalog.

**Comment by toudi** [comment]
tu jest chyba klasyczny przypadek "it's not a bug, it's a feature". domyślnie UPO zapisuje się w takim samym katalogu jak plik rejestru i ma nazwę {numerSesji}.pdf. staram się zrozumieć co byś chciał osiągnąć - zapisać UPO pod domyślną nazwą ale w innym katalogu ?

**Comment by kuncy7** [comment]
Dokładnie tak, zapisać UPO pod domyślną nazwą w innym katalogu.
Tak zrozumiałem ten komunikat: 
```
-o string
    	ścieżka do zapisu UPO (domyślnie katalog pliku statusu + {nrRef}.pdf)
```
Czyli opcja "-o" służy do zapisu UPO w dowolnym katalogu pod dowolną nazwą?

**Comment by toudi** [comment]
tak. zastanawiam się jak to sprytnie obsłużyć. chodzi mi o to, że jednocześnie chciałbym, żeby program potrafił stworzyć katalog jeśli go nie ma (tj żeby zadziałała składnia `-o nieistniejacy/katalog` a jednocześnie żeby obsługiwało ten schemat `{nrSesji}.pdf`. może po prostu rozbiję to na dwa switche tzn `-o` będzie oznaczało katalog a `-upoTmpl` albo coś podobnego będzie oznaczało nazwę pliku i wtedy będzie akceptowało składnię szablonową (z domyślną wartością `{sessionId}.pdf`

**Comment by kuncy7** [comment]
Ja to bym `nieistniejacy` katalog nie tworzył, bo ktoś się pomyli (jakaś kropka . czy coś w nazwie) i potem szukaj pliku na dysku. :)

**Comment by toudi** [comment]
zobacz czy teraz będzie lepiej [ 0.1.19 ] / https://ksef.po-godzinach.info/content/komendy/upo.html

**Comment by kuncy7** [comment]
Dla mnie super, lepiej tego nie można było zrobić! Dzięki! Zamykam to zgłoszenie.
